#version 450
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "simulate_header.glsl"

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() 
{
    uvec3 globalSize = gl_NumWorkGroups * gl_WorkGroupSize;
    uint index = gl_GlobalInvocationID.z * globalSize.x * globalSize.y + gl_GlobalInvocationID.y * globalSize.x + gl_GlobalInvocationID.x;
    if (index >= ubo.Nxyz) return;
    
    uint flagsn = flags[index]; 
    uint flagsn_bo = flagsn & TYPE_BO;
    uint flagsn_su = flagsn & TYPE_SU; 
    
    if(flagsn_bo == TYPE_S || flagsn_su == TYPE_G) return;
    
    bool is_outflow = ((flagsn & TYPE_X) != 0);
    
    uint nbs[Q];
    neighbors(index, nbs);
    
    float fhn[Q];
    load_f(index, fhn, nbs, ubo.t);

    if ((flagsn & TYPE_MS) == TYPE_MS) { 
        apply_moving_boundaries(fhn, nbs); 
    }
    
    float rhon, uxn, uyn, uzn; 
    
    if (is_outflow) {
        uvec3 xyz = coordinates(index);
        uint x0, xp, xm, y0, yp, ym, z0, zp, zm;
        calculate_indices(index, x0, xp, xm, y0, yp, ym, z0, zp, zm);
        
        uint inner_idx = index;
        if      (xyz.z == ubo.Nz - 1) inner_idx = x0 + y0 + zm;
        else if (xyz.z == 0)          inner_idx = x0 + y0 + zp;
        else if (xyz.x == ubo.Nx - 1) inner_idx = xm + y0 + z0;
        else if (xyz.x == 0)          inner_idx = xp + y0 + z0;
        else if (xyz.y == ubo.Ny - 1) inner_idx = x0 + ym + z0;
        else if (xyz.y == 0)          inner_idx = x0 + yp + z0;
        
        rhon = rhos[inner_idx];
        uxn  = vels[inner_idx];
        uyn  = vels[ubo.Nxyz + inner_idx];
        uzn  = vels[2u * ubo.Nxyz + inner_idx];
    } else if(flagsn_bo != TYPE_E) {
        calculate_rho_u(fhn, rhon, uxn, uyn, uzn); 
    }
    
    if(flagsn_bo != TYPE_E) {
        rhos[index]             = rhon; 
        vels[index]             = uxn; 
        vels[ubo.Nxyz + index]  = uyn;
        vels[2u * ubo.Nxyz + index] = uzn;
    }
}
