#version 450
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "simulate_header.glsl"

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() 
{
    uvec3 globalSize = gl_NumWorkGroups * gl_WorkGroupSize;
    uint index = gl_GlobalInvocationID.z * globalSize.x * globalSize.y + gl_GlobalInvocationID.y * globalSize.x + gl_GlobalInvocationID.x;
    if (index >= ubo.Nxyz) return;
    
    uint flagsn = flags[index]; // cache flags[n] for multiple readings
	uint flagsn_bo=flagsn&TYPE_BO, flagsn_su=flagsn&TYPE_SU; // extract boundary and surface flags
	if(flagsn_bo==TYPE_S||flagsn_su==TYPE_G) return; // if cell is solid boundary or gas, just return
    
    bool is_outflow = ((flagsn & TYPE_X) != 0); 

    uint nbs[Q];
    neighbors(index, nbs);
    
    float fhn[Q];
    load_f(index, fhn, nbs, ubo.t); // perform streaming (part 2);

    if (flagsn == TYPE_MS) { // MOVING_BOUNDARIES
        apply_moving_boundaries(fhn, nbs); // apply Dirichlet velocity boundaries if necessary (reads velocities of only neighboring boundary cells, which do not change during simulation)
    }

    float rhon, uxn, uyn, uzn; // calculate local density and velocity for collision
    
    if (is_outflow) {
        uint inner_idx = index;
        uvec3 xyz = coordinates(index);
        uint x0, xp, xm, y0, yp, ym, z0, zp, zm;
        calculate_indices(index, x0, xp, xm, y0, yp, ym, z0, zp, zm);

        if      (xyz.z == ubo.Nz - 1) inner_idx = x0 + y0 + zm;
        else if (xyz.z == 0)          inner_idx = x0 + y0 + zp;
        else if (xyz.x == ubo.Nx - 1) inner_idx = xm + y0 + z0;
        else if (xyz.x == 0)          inner_idx = xp + y0 + z0;
        else if (xyz.y == ubo.Ny - 1) inner_idx = x0 + ym + z0;
        else if (xyz.y == 0)          inner_idx = x0 + yp + z0;

        rhon = rhos[inner_idx];
        uxn  = vels[inner_idx];
        uyn  = vels[ubo.Nxyz + inner_idx];
        uzn  = vels[2u * ubo.Nxyz + inner_idx];
    } else if(flagsn_bo==TYPE_E) {
        rhon = rhos[            index]; // apply preset velocity/density
        uxn  = vels[            index];
        uyn  = vels[   ubo.Nxyz+index];
        uzn  = vels[2u*ubo.Nxyz+index];
    } else {
        calculate_rho_u(fhn, rhon, uxn, uyn, uzn); // calculate density and velocity fields from fi
    }
    
    float fxn=ubo.fx, fyn=ubo.fy, fzn=ubo.fz; // force starts as constant volume force, can be modified before call of calculate_forcing_terms(...)
    float Fin[Q]; // forcing terms
    
    // FORCE_FIELD
    { // separate block to avoid variable name conflicts
		fxn += float(bfs[            index]); // apply force field
		fyn += float(bfs[   ubo.Nxyz+index]);
		fzn += float(bfs[2u*ubo.Nxyz+index]);
	}

    // VOLUME_FORCE
    {
        const float rho2 = 0.5f/rhon; // apply external volume force (Guo forcing, Krueger p.233f)
		uxn = clamp(fma(fxn, rho2, uxn), -def_c, def_c); // limit velocity (for stability purposes)
		uyn = clamp(fma(fyn, rho2, uyn), -def_c, def_c); // force term: F*dt/(2*rho)
		uzn = clamp(fma(fzn, rho2, uzn), -def_c, def_c);
		calculate_forcing_terms(uxn, uyn, uzn, fxn, fyn, fzn, Fin); // calculate volume force terms Fin from velocity field (Guo forcing, Krueger p.233f)
    }

    // EQUILIBRIUM BOUNDARIES
    if(flagsn_bo!=TYPE_E) { // only update fields for non-TYPE_E cells
        rhos[            index] = rhon; // update density field
        vels[            index] = uxn; // update velocity field
        vels[   ubo.Nxyz+index] = uyn;
        vels[2u*ubo.Nxyz+index] = uzn;
    }
    
    float feq[Q]; // equilibrium DDFs
    calculate_f_eq(rhon, uxn, uyn, uzn, feq); // calculate equilibrium DDFs
    float w = ubo.inv_tau; // LBM relaxation rate w = dt/tau = dt/(nu/c^2+dt/2) = 1/(3*nu+1/2)
    
    // SUBGRID
    { // Smagorinsky-Lilly subgrid turbulence model, source: https://arxiv.org/pdf/comp-gas/9401004.pdf, in the eq. below (26), it is "tau_0" not "nu_0", and "sqrt(2)/rho" (they call "rho" "n") is missing
		const float tau0 = 1.0f/w; // source 2: https://youtu.be/V8ydRrdCzl0
		float Hxx=0.0f, Hyy=0.0f, Hzz=0.0f, Hxy=0.0f, Hxz=0.0f, Hyz=0.0f; // non-equilibrium stress tensor
		for(uint q=1u; q<Q; q++) {
			const float fneqi = fhn[q]-feq[q];
			const float cxi=c(q), cyi=c(Q+q), czi=c(2u*Q+q);
			Hxx += cxi*cxi*fneqi; //Hyx += cyi*cxi*fneqi; Hzx += czi*cxi*fneqi; // symmetric tensor
			Hxy += cxi*cyi*fneqi; Hyy += cyi*cyi*fneqi; //Hzy += czi*cyi*fneqi;
			Hxz += cxi*czi*fneqi; Hyz += cyi*czi*fneqi; Hzz += czi*czi*fneqi;
		}
		const float Q0 = sq(Hxx)+sq(Hyy)+sq(Hzz)+2.0f*(sq(Hxy)+sq(Hxz)+sq(Hyz)); // Q = H*H, turbulent eddy viscosity nut = (C*Delta)^2*|S|, intensity of local strain rate tensor |S|=sqrt(2*S*S)
		w = 2.0f/(tau0+sqrt(sq(tau0)+0.76421222f*sqrt(Q0)/rhon)); // 0.76421222 = 18*sqrt(2)*(C*Delta)^2, C = 1/pi*(2/(3*CK))^(3/4) = Smagorinsky-Lilly constant, CK = 3/2 = Kolmogorov constant, Delta = 1 = lattice constant
	} // modity LBM relaxation rate by increasing effective viscosity in regions of high strain rate (add turbulent eddy viscosity), nu_eff = nu_0+nu_t
    
    const float c_tau = fma(w, -0.5f, 1.0f);
	for(uint q=0u; q<Q; q++) Fin[q] *= c_tau;
    for(uint q=0u; q<Q; q++) fhn[q] = flagsn_bo==TYPE_E || is_outflow ? feq[q] : fma(1.0f-w, fhn[q], fma(w, feq[q], Fin[q])); // perform collision (SRT)

    store_f(index, fhn, nbs, ubo.t); // perform streaming (part 1)
}
