#version 450
#extension GL_EXT_shader_atomic_float : require
#extension GL_EXT_scalar_block_layout : require

struct LagrangianPoint {
    vec4 position;
};

struct LagrangianData {
    vec4 velocity;
    vec4 force;
};

layout (std430, binding = 0) uniform SimulateUBO {
    uint Nx;
    uint Ny;
    uint Nz;
    uint Nxyz;
    uint particleCount;
    float particleRho;
    float niu;
    float tau;
    float inv_tau;
    float fx;
    float fy;
    float fz;
    float dt;
    uint t;
    uint render_mode;
    uint fixed_point_iteration;
    uint lagrangianPointCount;
    mat4 modelMatrix;
} ubo;

layout(std430, binding = 8) buffer LagrangianDataBuffer {
    LagrangianData lagrangianData[];
};

layout(std430, binding = 9) buffer LagrangianPointsRest {
    LagrangianPoint lagrangianPoints_Rest[];
};

layout(std430, binding = 12) buffer TotalForceTorqueBuffer {
    vec4 total_force;
    vec4 total_torque;
};

#define WORKGROUP_SIZE 256
layout (local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

shared vec3 s_force[WORKGROUP_SIZE];
shared vec3 s_torque[WORKGROUP_SIZE];

void main() {
    uint local_id = gl_LocalInvocationID.x;
    uint global_id = gl_GlobalInvocationID.x;

    vec3 force_on_point = vec3(0.0);
    vec3 torque_on_point = vec3(0.0);

    if (global_id < ubo.lagrangianPointCount) {
        force_on_point = -lagrangianData[global_id].force.xyz;
        
        vec3 r_rest = lagrangianPoints_Rest[global_id].position.xyz;
        vec3 r_world = mat3(ubo.modelMatrix) * r_rest; 
        torque_on_point = cross(r_world, force_on_point);
    }

    s_force[local_id] = force_on_point;
    s_torque[local_id] = torque_on_point;

    barrier();

    for (uint s = WORKGROUP_SIZE / 2; s > 0; s >>= 1) {
        if (local_id < s) {
            s_force[local_id] += s_force[local_id + s];
            s_torque[local_id] += s_torque[local_id + s];
        }
        barrier();
    }

    if (local_id == 0) {
        atomicAdd(total_force.x, s_force[0].x);
        atomicAdd(total_force.y, s_force[0].y);
        atomicAdd(total_force.z, s_force[0].z);

        atomicAdd(total_torque.x, s_torque[0].x);
        atomicAdd(total_torque.y, s_torque[0].y);
        atomicAdd(total_torque.z, s_torque[0].z);
    }
}
