#version 450
#extension GL_EXT_shader_atomic_float : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "simulate_header.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint k = gl_GlobalInvocationID.x;
    if (k >= ubo.lagrangianPointCount) return;

    vec3 point_pos = lagrangianPoints[k].position.xyz;

    bool is_last_iteration = (ubo.fixed_point_iteration == 4);

    vec3 force_to_spread;
    if (is_last_iteration) {
        force_to_spread = lagrangianData[k].force.xyz;
    } else {
        force_to_spread = tempForces[k].xyz;
    }

    ivec3 center_cell = ivec3(round(point_pos));
    for (int i = -2; i <= 2; ++i) {
    for (int j = -2; j <= 2; ++j) {
    for (int k_cell = -2; k_cell <= 2; ++k_cell) {
        ivec3 cell_coord = center_cell + ivec3(i, j, k_cell);

        if (any(lessThan(cell_coord, ivec3(0))) || any(greaterThanEqual(cell_coord, ivec3(ubo.Nx, ubo.Ny, ubo.Nz)))) {
            continue;
        }

        uint fluid_index = cell_coord.z * ubo.Nx * ubo.Ny + cell_coord.y * ubo.Nx + cell_coord.x;
        vec3 fluid_pos = vec3(cell_coord);

        float weight = compute_weight_3d(point_pos, fluid_pos);
        if (weight == 0.0) continue;

        vec3 force_on_cell = force_to_spread * weight;

        if (is_last_iteration) {
            atomicAdd(bfs[fluid_index],               force_on_cell.x);
            atomicAdd(bfs[ubo.Nxyz + fluid_index],    force_on_cell.y);
            atomicAdd(bfs[2 * ubo.Nxyz + fluid_index],force_on_cell.z);
        } else {
            atomicAdd(tempVels[fluid_index],               force_on_cell.x);
            atomicAdd(tempVels[ubo.Nxyz + fluid_index],    force_on_cell.y);
            atomicAdd(tempVels[2 * ubo.Nxyz + fluid_index],force_on_cell.z);
        }
    }}}
}
