#version 450
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "simulate_header.glsl"

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uvec3 globalSize = gl_NumWorkGroups * gl_WorkGroupSize;
    uint index = gl_GlobalInvocationID.z * globalSize.x * globalSize.y + gl_GlobalInvocationID.y * globalSize.x + gl_GlobalInvocationID.x;
    if (index >= ubo.Nxyz) return;

    uint flagsn = flags[index];
    uint flagsn_bo = flagsn & TYPE_BO; // extract boundary flags

    uint nbs[Q]; // neighbor indices
    neighbors(index, nbs); // calculate neighbor indices

    uint nbflags[Q]; // cache neighbor flags for multiple readings
    for(uint q=1u; q<Q; q++) nbflags[q] = flags[nbs[q]];

    if(flagsn_bo==TYPE_S) { // cell is solid
		bool TYPE_ONLY_S = true; // has only solid neighbors
		for(uint q=1u; q<Q; q++) TYPE_ONLY_S = TYPE_ONLY_S&&(nbflags[q]&TYPE_BO)==TYPE_S;
		if(TYPE_ONLY_S) {
			vels[            index] = 0.0f; // reset velocity for solid lattice points with only boundary neighbors
			vels[   ubo.Nxyz+index] = 0.0f;
			vels[2u*ubo.Nxyz+index] = 0.0f;
		}
    }else if (flagsn_bo!=TYPE_E) {
        bool next_to_moving_boundary = false;
		for(uint q=1u; q<Q; q++) {
			next_to_moving_boundary = next_to_moving_boundary||((nbflags[q]&TYPE_BO)==TYPE_S&&(vels[nbs[q]]!=0.0f||vels[ubo.Nxyz+nbs[q]]!=0.0f||vels[2u*ubo.Nxyz+nbs[q]]!=0.0f));
		}
		flags[index] = flagsn = next_to_moving_boundary ? flagsn|TYPE_MS : flagsn&~TYPE_MS; // mark/unmark cells next to TYPE_S cells with velocity!=0 with TYPE_MS
    }

    float feq[Q]; // f_equilibrium
	calculate_f_eq(rhos[index], vels[index], vels[ubo.Nxyz+index], vels[2u*ubo.Nxyz+index], feq);

    store_f(index, feq, nbs, 1u); // write to fi
}
