#version 450
#extension GL_EXT_shader_atomic_float : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "simulate_header.glsl"

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint k = gl_GlobalInvocationID.x;
    if (k >= ubo.lagrangianPointCount) return;

    uint bodyIdx = bodyIndices[k];
    if (bodyIdx >= ubo.rigidBodyCount) return;

    vec4 rest_pos = lagrangianPoints_Rest[k].position;

    vec4 current_world_pos = bodies[bodyIdx].modelMatrix * rest_pos;

    vec3 prev_world_pos = lagrangianPoints_Prev[k].position.xyz;

    vec3 target_vel_k = (current_world_pos.xyz - prev_world_pos) * ubo.couplingStrength;

    lagrangianPoints[k].position = current_world_pos;
    if (ubo.t != 0) {
        lagrangianData[k].velocity.xyz = target_vel_k;
    }
}
